"""Update models

Revision ID: 0cf41ae0f66a
Revises: 4fb754983966
Create Date: 2024-02-18 18:04:34.640269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf41ae0f66a'
down_revision = '4fb754983966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('about_img', sa.String(), nullable=True),
    sa.Column('mission', sa.String(), nullable=True),
    sa.Column('vision', sa.String(), nullable=True),
    sa.Column('faith', sa.String(), nullable=True),
    sa.Column('faith_img', sa.String(), nullable=True),
    sa.Column('word', sa.String(), nullable=True),
    sa.Column('word_img', sa.String(), nullable=True),
    sa.Column('trinity', sa.String(), nullable=True),
    sa.Column('trinity_img', sa.String(), nullable=True),
    sa.Column('baptism', sa.String(), nullable=True),
    sa.Column('baptism_img', sa.String(), nullable=True),
    sa.Column('church_slogan', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('history_desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('department_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('departments')
    op.drop_table('about_us')
    # ### end Alembic commands ###
