"""update models

Revision ID: 2b652c32f764
Revises: 9f8d19a7f99f
Create Date: 2024-02-21 17:19:58.693857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b652c32f764'
down_revision = '9f8d19a7f99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('blog_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sliderimages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slider1', sa.String(), nullable=True),
    sa.Column('slider2', sa.String(), nullable=True),
    sa.Column('slider3', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('church_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(), nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_img', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('event_category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('scripture', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('event_host', sa.String(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('event_host')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('date')
        batch_op.drop_column('location')
        batch_op.drop_column('scripture')
        batch_op.drop_column('theme')
        batch_op.drop_column('event_category')
        batch_op.drop_column('event_img')

    with op.batch_alter_table('church_info', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('email')
        batch_op.drop_column('address')

    op.drop_table('sliderimages')
    op.drop_table('blogs')
    # ### end Alembic commands ###
