"""Update models

Revision ID: 8f7ccc221137
Revises: 77fc01575db3
Create Date: 2024-02-19 07:49:29.329701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7ccc221137'
down_revision = '77fc01575db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('youtube_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tiktok_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('x_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('tiktok')
        batch_op.drop_column('facebook')
        batch_op.drop_column('youtube')
        batch_op.drop_column('instagram')
        batch_op.drop_column('x_social')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=64), nullable=False))
        batch_op.drop_index('ix_users_secondname')
        batch_op.create_index(batch_op.f('ix_users_lastname'), ['lastname'], unique=False)
        batch_op.drop_column('secondname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondname', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_lastname'))
        batch_op.create_index('ix_users_secondname', ['secondname'], unique=False)
        batch_op.drop_column('lastname')

    with op.batch_alter_table('church_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x_social', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('youtube', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('tiktok', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('x_url')
        batch_op.drop_column('tiktok_url')
        batch_op.drop_column('youtube_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('facebook_url')

    # ### end Alembic commands ###
