"""Update Service model

Revision ID: c15b8311912c
Revises: 2b07b5e0a471
Create Date: 2024-02-16 15:48:31.887742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15b8311912c'
down_revision = '2b07b5e0a471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.TIME(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.String(),
               type_=sa.TIME(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.String(),
               type_=sa.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
