"""Create Service, ChurchInfo models

Revision ID: d06fc0ea3fbb
Revises: d6dc1f654007
Create Date: 2024-02-16 13:16:08.415798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06fc0ea3fbb'
down_revision = 'd6dc1f654007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('church_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('youtube', sa.String(length=255), nullable=True),
    sa.Column('tiktok', sa.String(length=255), nullable=True),
    sa.Column('x_social', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('secondname', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_firstname'), ['firstname'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_secondname'), ['secondname'], unique=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_secondname'))
        batch_op.drop_index(batch_op.f('ix_users_firstname'))
        batch_op.create_index('ix_users_username', ['username'], unique=1)
        batch_op.drop_column('secondname')
        batch_op.drop_column('firstname')

    op.drop_table('services')
    op.drop_table('church_info')
    # ### end Alembic commands ###
