"""update SliderImage model

Revision ID: dfa74fe16c09
Revises: 2b652c32f764
Create Date: 2024-02-21 18:20:15.831899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa74fe16c09'
down_revision = '2b652c32f764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sliderimages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slider_img', sa.String(), nullable=True))
        batch_op.drop_column('slider3')
        batch_op.drop_column('slider1')
        batch_op.drop_column('slider2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sliderimages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slider2', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('slider1', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('slider3', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('slider_img')

    # ### end Alembic commands ###
